server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  dubbo:
    application:
      name: dubbo-provider
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      port: 29014
    scan: com.nfsq.yqf.dubboprovider.service
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: bean
